# Numpy Library와 Array


# Numpy Library 설치

In [ ]:
pip uninstall numpy --y

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4


In [ ]:
pip install numpy==1.23.5

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 64.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albucore 0.0.19 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
albumentations 1.4.20 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
bigframes 1.26.0 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
chex 0.1.87 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
jax 0.4.33 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
jaxlib 0.4.33 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
xarray 2024.10.0 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.


In [ ]:
pip list | grep numpy

numpy                              1.23.5


# Library Load
- numpy libirary는 load할때 as를 붙여 np라는 별칭으로 import 합니다.

In [ ]:
import numpy as np

# Array 생성
```python
np.array(data)
```

## (1)1차원 Array 생성

In [ ]:
arr_1 = np.array([1,2,3,4])

In [ ]:
print(arr_1)

[1 2 3 4]


In [ ]:
type(arr_1)

numpy.ndarray

## (2)2차원 Array 생성

In [ ]:
arr_2 = np.array([
    [1,2,3],
    [2,3,4]
])

In [ ]:
print(arr_2)

[[1 2 3]
 [2 3 4]]


## (3)3차원 Array 생성

In [ ]:
arr_3 = np.array([
    [[1,2,3], [3,4,5], [10,20,30]],
    [[4,5,6], [7,9,8], [15,54,78]],
    [[1,2,3], [3,4,5], [5121,999,989.0]]
])

In [ ]:
print(arr_3)

[[[1.000e+00 2.000e+00 3.000e+00]
  [3.000e+00 4.000e+00 5.000e+00]
  [1.000e+01 2.000e+01 3.000e+01]]

 [[4.000e+00 5.000e+00 6.000e+00]
  [7.000e+00 9.000e+00 8.000e+00]
  [1.500e+01 5.400e+01 7.800e+01]]

 [[1.000e+00 2.000e+00 3.000e+00]
  [3.000e+00 4.000e+00 5.000e+00]
  [5.121e+03 9.990e+02 9.890e+02]]]


## (4)1로 채워진 Array 생성
```python
np.ones(shape, 데이터타입)
```

In [ ]:
arr_4 = np.ones((3,4), int)

In [ ]:
print(arr_4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## (5)0으로 채워진 Array 생성
```python
np.zeros(shape, 데이터타입)
```

In [ ]:
arr_5 = np.zeros((3,5,5), 'float')

In [ ]:
print(arr_5)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


## (6)임의의 값으로 채워진 Array 생성

In [ ]:
arr_6 = np.random.random((4,5))

In [ ]:
print(arr_6)

[[0.59687376 0.96901757 0.59050628 0.25164658 0.5717859 ]
 [0.45719433 0.98344015 0.48174382 0.11555954 0.26156716]
 [0.2239679  0.4907871  0.63486947 0.20578387 0.44663686]
 [0.32219367 0.48051619 0.09723781 0.19861686 0.79377178]]


# Array 정보 확인하기

## (1)Array 모양 확인하기


In [ ]:
print(arr_1.shape)

(4,)


In [ ]:
print(arr_2.shape)

(2, 3)


In [ ]:
print(arr_3.shape)

(3, 3, 3)


## (2)Array dtype 확인하기


In [ ]:
print(arr_1.dtype)

int64


In [ ]:
print(arr_2.dtype)

int64


In [ ]:
print(arr_3.dtype)

float64


In [ ]:
print(arr_3)

[[[1.000e+00 2.000e+00 3.000e+00]
  [3.000e+00 4.000e+00 5.000e+00]
  [1.000e+01 2.000e+01 3.000e+01]]

 [[4.000e+00 5.000e+00 6.000e+00]
  [7.000e+00 9.000e+00 8.000e+00]
  [1.500e+01 5.400e+01 7.800e+01]]

 [[1.000e+00 2.000e+00 3.000e+00]
  [3.000e+00 4.000e+00 5.000e+00]
  [5.121e+03 9.990e+02 9.890e+02]]]


# Array Data Handling

## (1)Array의 Dtype 변경하기


In [ ]:
arr_3.astype(np.int8)

array([[[  1,   2,   3],
        [  3,   4,   5],
        [ 10,  20,  30]],

       [[  4,   5,   6],
        [  7,   9,   8],
        [ 15,  54,  78]],

       [[  1,   2,   3],
        [  3,   4,   5],
        [  1, -25, -35]]], dtype=int8)

In [ ]:
arr_3

array([[[1.000e+00, 2.000e+00, 3.000e+00],
        [3.000e+00, 4.000e+00, 5.000e+00],
        [1.000e+01, 2.000e+01, 3.000e+01]],

       [[4.000e+00, 5.000e+00, 6.000e+00],
        [7.000e+00, 9.000e+00, 8.000e+00],
        [1.500e+01, 5.400e+01, 7.800e+01]],

       [[1.000e+00, 2.000e+00, 3.000e+00],
        [3.000e+00, 4.000e+00, 5.000e+00],
        [5.121e+03, 9.990e+02, 9.890e+02]]])

In [ ]:
arr_3 = arr_3.astype("int")

In [ ]:
print(arr_3.dtype)

int64


In [ ]:
print(arr_3)

[[[   1    2    3]
  [   3    4    5]
  [  10   20   30]]

 [[   4    5    6]
  [   7    9    8]
  [  15   54   78]]

 [[   1    2    3]
  [   3    4    5]
  [5121  999  989]]]


## (2)Array Shape 변경하기

### 행, 열을 명시적으로 입력하여 shape 변경

In [ ]:
arr = np.array([
    [1,2,3,4,5,6],
    [10,20,30,40,50,60],
    [100,50,35,48,64,70],
    [10,20,30,40,50,60]
])

In [ ]:
arr.shape

(4, 6)

In [ ]:
arr.reshape(3,8)

array([[  1,   2,   3,   4,   5,   6,  10,  20],
       [ 30,  40,  50,  60, 100,  50,  35,  48],
       [ 64,  70,  10,  20,  30,  40,  50,  60]])

In [ ]:
arr

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100,  50,  35,  48,  64,  70],
       [ 10,  20,  30,  40,  50,  60]])

In [ ]:
arr_2 = arr.reshape(3,8)

In [ ]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [ ]:
print(arr_2)

[[  1   2   3   4   5   6  10  20]
 [ 30  40  50  60 100  50  35  48]
 [ 64  70  10  20  30  40  50  60]]


In [ ]:
print(arr_2.shape)

(3, 8)


### 행, 열 중 하나의 값만 넣어서 shape 변경

In [ ]:
arr_3 = arr.reshape(2, -1)

In [ ]:
print(arr_3.shape)

(2, 12)


In [ ]:
arr_4 = arr_2.reshape(-1, 6)

In [ ]:
print(arr_4.shape)

(4, 6)


## (3)Array 인덱싱

In [ ]:
arr = np.array([[ 7, 34, 94, 24, 60],
                [56, 34, 87, 59, 66],
                [14, 44, 19, 51, 78],
                [90, 22, 43, 91, 62],
                [84, 78, 22,  8, 62]])

### array row 인덱싱

In [ ]:
arr[3]

array([90, 22, 43, 91, 62])

In [ ]:
arr[0]

array([ 7, 34, 94, 24, 60])

### arr row & column 인덱싱

In [ ]:
arr[3,3]

91

In [ ]:
arr[3][3]

91

In [ ]:
arr[-2][-2]

91

## (4)Array 슬라이싱

In [ ]:
arr= np.array([[98, 73, 15, 74,  5],
              [16, 26, 75, 79, 30],
              [39, 65, 54, 72, 82],
              [70, 63, 79, 24, 86],
              [91, 13, 28, 87, 52]])

### array row slicing

In [ ]:
arr[0:3]

array([[98, 73, 15, 74,  5],
       [16, 26, 75, 79, 30],
       [39, 65, 54, 72, 82]])

In [ ]:
arr[2:-1]

array([[39, 65, 54, 72, 82],
       [70, 63, 79, 24, 86]])

### array column slicing

In [ ]:
arr[:, 2:-1]

array([[15, 74],
       [75, 79],
       [54, 72],
       [79, 24],
       [28, 87]])

## (5)조건에 따라 Array 인덱싱하기

In [ ]:
arr= np.array([[98, 73, 15, 74,  5],
              [16, 26, 75, 79, 30],
              [39, 65, 54, 72, 82],
              [70, 63, 79, 24, 86],
              [91, 13, 28, 87, 52]])

In [ ]:
arr[ arr > 40 ]

array([98, 73, 74, 75, 79, 65, 54, 72, 82, 70, 63, 79, 86, 91, 87, 52])

In [ ]:
arr[ arr < 20 ]

array([15,  5, 16, 13])

In [ ]:
arr[(arr < 40) & (arr >20)]

array([26, 30, 39, 24, 28])

In [ ]:
arr[(arr > 40) | (arr <20)]

### 조건에 따라 Array의 값을 조작하기

In [ ]:
arr= np.array([[98, 73, 15, 74,  5],
              [16, 26, 75, 79, 30],
              [39, 65, 54, 72, 82],
              [70, 63, 79, 24, 86],
              [91, 13, 28, 87, 52]])

In [ ]:
arr_2 = np.where(arr> 70, 0, arr)

In [ ]:
arr_2

array([[ 0,  0, 15,  0,  5],
       [16, 26,  0,  0, 30],
       [39, 65, 54,  0,  0],
       [70, 63,  0, 24,  0],
       [ 0, 13, 28,  0, 52]])

In [ ]:
arr_3 = np.where(arr>70, arr, 1)

In [ ]:
arr_3

array([[98, 73,  1, 74,  1],
       [ 1,  1, 75, 79,  1],
       [ 1,  1,  1, 72, 82],
       [ 1,  1, 79,  1, 86],
       [91,  1,  1, 87,  1]])

In [ ]:
arr_4 = np.where(arr> 70, arr, -arr)

In [ ]:
arr_4

array([[ 98,  73, -15,  74,  -5],
       [-16, -26,  75,  79, -30],
       [-39, -65, -54,  72,  82],
       [-70, -63,  79, -24,  86],
       [ 91, -13, -28,  87, -52]])

## (6)Array 연산

### Array 사칙 연산

In [ ]:
x = np.array([[98, 73, 15, 74,  5],
              [16, 26, 75, 79, 30],
              [39, 65, 54, 72, 82],
              [70, 63, 79, 24, 86],
              [91, 13, 28, 87, 52]])

In [ ]:
y = np.array([[12, 57, 61, 13, 29],
              [ 9, 96,  5, 30, 21],
              [ 9, 90,  5, 18, 45],
              [75, 11, 79, 33, 31],
              [ 5, 24,  1, 12, 93]])

#### array 덧셈연산

In [ ]:
x + y

array([[110, 130,  76,  87,  34],
       [ 25, 122,  80, 109,  51],
       [ 48, 155,  59,  90, 127],
       [145,  74, 158,  57, 117],
       [ 96,  37,  29,  99, 145]])

#### array 뺄셈연산

In [ ]:
x - y

array([[ 86,  16, -46,  61, -24],
       [  7, -70,  70,  49,   9],
       [ 30, -25,  49,  54,  37],
       [ -5,  52,   0,  -9,  55],
       [ 86, -11,  27,  75, -41]])

#### array 곱셈 연산

In [ ]:
x * y

array([[1176, 4161,  915,  962,  145],
       [ 144, 2496,  375, 2370,  630],
       [ 351, 5850,  270, 1296, 3690],
       [5250,  693, 6241,  792, 2666],
       [ 455,  312,   28, 1044, 4836]])

#### array 나눗셈 연산

In [ ]:
x / y

array([[ 8.16666667,  1.28070175,  0.24590164,  5.69230769,  0.17241379],
       [ 1.77777778,  0.27083333, 15.        ,  2.63333333,  1.42857143],
       [ 4.33333333,  0.72222222, 10.8       ,  4.        ,  1.82222222],
       [ 0.93333333,  5.72727273,  1.        ,  0.72727273,  2.77419355],
       [18.2       ,  0.54166667, 28.        ,  7.25      ,  0.55913978]])

#### array 제곱 연산

In [ ]:
x ** 2

array([[9604, 5329,  225, 5476,   25],
       [ 256,  676, 5625, 6241,  900],
       [1521, 4225, 2916, 5184, 6724],
       [4900, 3969, 6241,  576, 7396],
       [8281,  169,  784, 7569, 2704]])

In [ ]:
x * 2

array([[196, 146,  30, 148,  10],
       [ 32,  52, 150, 158,  60],
       [ 78, 130, 108, 144, 164],
       [140, 126, 158,  48, 172],
       [182,  26,  56, 174, 104]])

### Array Dot product 연산

In [ ]:
arr_1 = np.random.randint(1, 20, (2, 4))

In [ ]:
arr_2 = np.random.randint(1, 20, (4, 2))

In [ ]:
arr_1

array([[12, 12,  1, 13],
       [12,  6,  3,  8]])

In [ ]:
arr_2

array([[ 5,  6],
       [ 3, 15],
       [ 9,  9],
       [ 5, 10]])

In [ ]:
np.dot(arr_1, arr_2)

array([[170, 391],
       [145, 269]])

### Array Transpose 연산

In [ ]:
arr = np.array([[98, 73, 15, 74,  5],
                [16, 26, 75, 79, 30],
                [39, 65, 54, 72, 82],
                [70, 63, 79, 24, 86],
                [91, 13, 28, 87, 52]])

In [ ]:
arr.T

array([[98, 16, 39, 70, 91],
       [73, 26, 65, 63, 13],
       [15, 75, 54, 79, 28],
       [74, 79, 72, 24, 87],
       [ 5, 30, 82, 86, 52]])

In [ ]:
X  = np.random.randint(1, 20, (2, 4))
W = np.random.randint(1, 20, (2, 4))

In [ ]:
np.dot(X, W.T)

array([[201, 245],
       [402, 372]])

### Array shuffle

In [ ]:
arr = np.array([[98, 73, 15, 74,  5],
                [16, 26, 75, 79, 30],
                [39, 65, 54, 72, 82],
                [70, 63, 79, 24, 86],
                [91, 13, 28, 87, 52]])

In [ ]:
np.random.shuffle(arr)

In [ ]:
print(arr)

[[98 73 15 74  5]
 [39 65 54 72 82]
 [16 26 75 79 30]
 [91 13 28 87 52]
 [70 63 79 24 86]]


### Array Sampling


In [ ]:
arr = np.array([[98, 73, 15, 74,  5],
                [16, 26, 75, 79, 30],
                [39, 65, 54, 72, 82],
                [70, 63, 79, 24, 86],
                [91, 13, 28, 87, 52]])

In [ ]:
np.random.choice(arr, 3)

ValueError: a must be 1-dimensional

In [ ]:
arr = arr.flatten()

In [ ]:
arr.shape

(25,)

#### 복원추출

In [ ]:
np.random.choice(arr, 3)

array([98, 79, 91])

In [ ]:
np.random.choice(arr, 3)

array([28, 54, 26])

In [ ]:
np.random.choice(arr, 3)

array([39, 39, 74])

#### 비복원추출

In [ ]:
np.random.choice(arr, 3, replace = False)

array([79, 63, 39])