# Numpy Library로 Perceptron 구현해보기
- Perceptron은 Input X를 입력으로 받고, Weight vector의 Transpose와의 dot product을 수행한 후 bias term을 더해 출력을 만들고, activation function에 통과시켜 최종 결과물을 출력합니다.

<img src = "https://velog.velcdn.com/images%2Fvhehduatks%2Fpost%2F8d4e2053-69f5-45b9-8b2a-c7eb16d9f326%2Fimage.png" height = "400px">

## Q1. 임의의 input vector X를 numpy array로 정의하세요.
- 단, X의 column축 차원은 10개로 가정하고, 입력데이터 X의 row축 데이터는 100개로 가정합니다.
- X의 element value는 1~1000 사이의 정수값을 가집니다.

In [ ]:
import numpy as np

X = np.random.randint(low = 1, high = 1000, size = (100, 10))

In [ ]:
X.shape

(100, 10)

## Q2. 임의의 Weight Vector W를 numpy array로 정의하세요
- 단, W의 row축 차원은 input X의 row축 데이터의 개수이며, W의 Column축 차원은 1로 가정합니다.
- W의 값은 0~1 사이의 랜덤한 값을 갖습니다.

In [ ]:
W = np.random.random(size=(100,1))

In [ ]:
W.shape

(100, 1)

## Q3. W와 X의 shape을 고려하여, bias vector B를 numpy array로 정의하세요
- 단, B의 element value는 0~1의 랜덤한 값을 가집니다.

In [ ]:
B = np.random.random(size = (1, 10))

## Q4. Matrix의 칼럼단위의 Min-Max Scaling 함수를 정의하고, Input Vector X에 대해 각 칼럼별로 Min-Max Scaling을 적용하세요
- Min-Max Scaling의 수식은 다음과 같습니다.

  <img src = "https://blog.kakaocdn.net/dn/bOOjFS/btrMp3CJGMI/clCAK4huytiEEiLDAVKgjK/img.png" height = "150px">

In [ ]:
X_sc = X.copy()

In [ ]:
X_sc[:, 0] -  X_sc[:, 0].max()

array([ -54, -537, -776, -786, -761,  -93, -541, -370, -874, -575, -898,
       -806, -605, -554, -720,  -18, -355, -853, -119, -276, -223, -182,
       -954, -486, -830, -272, -105, -919, -819, -159, -188,  -43,  -80,
       -293,  -69, -910, -322, -967,    0, -950, -663, -568, -119, -648,
        -90, -547,  -20, -117, -519, -822,  -74, -937, -403, -971, -895,
        -43,  -23, -401,  -78, -612, -182, -573,  -23, -985, -639, -943,
       -917, -314, -654, -334, -348, -406, -862, -953, -949, -676, -470,
       -542, -166, -545, -586, -638, -290, -928, -740, -458, -747, -763,
       -889, -838, -175, -509, -154, -508, -738, -676,   -7, -794, -496,
       -674])

In [ ]:
def min_max_scaler(x_col):
  x_max = x_col.max()
  x_min = x_col.min()

  x_col_scaled = (x_col - x_min) / (x_max - x_min)
  return x_col_scaled



In [ ]:
X_sc = X_sc.astype("float")

In [ ]:
for i in range(X_sc.shape[1]):
  X_sc[:, i] = min_max_scaler(X_sc[:, i])

In [ ]:
X_sc

array([[0.21068548, 0.59137577, 0.18565401, 0.45555556, 0.3825641 ,
        0.62002043, 0.47894737, 0.93304061, 0.23630832, 0.30823293],
       [0.38810484, 0.18583162, 0.38291139, 0.43131313, 0.06461538,
        0.80898876, 0.17263158, 0.87815587, 0.6703854 , 0.85140562],
       [0.30947581, 0.31519507, 0.16666667, 0.24646465, 0.87589744,
        0.23697651, 0.35052632, 0.99670692, 0.74340771, 0.50301205],
       [0.88508065, 0.0338809 , 0.77109705, 0.58989899, 0.49128205,
        0.28089888, 0.88631579, 0.77936334, 0.62068966, 0.58433735],
       [0.30745968, 0.29876797, 0.73523207, 0.88080808, 0.51282051,
        0.07456588, 0.78      , 0.73874863, 0.94624746, 0.17771084],
       [0.34274194, 0.59342916, 0.657173  , 0.42020202, 0.8974359 ,
        0.04494382, 0.16631579, 0.29527991, 0.76876268, 0.9437751 ],
       [0.62802419, 0.4486653 , 0.06540084, 0.88383838, 0.52512821,
        0.72931563, 0.99578947, 0.6377607 , 0.14807302, 0.50502008],
       [0.76108871, 0.88193018, 0.0696202

In [ ]:
X_sc.max(), X_sc.min()

(1.0, 0.0)

## Q5. Weight vector W에 대해 Transpose연산을 수행하고, Scaling을 적용한 Input X와 dot product를 구한 후 bias vector를 더해서 output vector Y를 구하세요

In [ ]:
W.T.shape

(1, 100)

In [ ]:
X.shape

(100, 10)

In [ ]:
Y = np.dot(W.T, X_sc) + B

## Q6. Sigmoid function을 정의하고, Sigmoid function에 Y를 입력하고 최종 output vector Y_final을 구해보세요
- Sigmoid function의 수식은 다음과 같습니다.
  <img src = "https://media.licdn.com/dms/image/D4D12AQGIXdSG7IJCNw/article-cover_image-shrink_600_2000/0/1694183259537?e=2147483647&v=beta&t=OtnfeqwCtKTSVrdKZdyOzNYECyLLZuEUIxkTfTQ0dS0" height = "300px">

- exponential 함수를 어떻게 사용하는지 googling을 통해 search해봅시다!

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-1 * x))

In [ ]:
Y_pred = sigmoid(Y)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])